name: Publish Docs

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Fetch tags
        run: git fetch --tags

      - name: Publish documentation with goreleaser
        run: |
          go install github.com/goreleaser/goreleaser@v0.180.0
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} goreleaser release --rm-dist --snapshot --skip-publish
